version: '3.9'

services:
  flyway:
    image: redgate/flyway
    #command: -licenseKey="FL01..." -url=jdbc:postgresql://db:5432/coupon -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./conf/flyway.conf:/flyway/conf/flyway.config
      - ./sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.6
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
       POSTGRES_PASSWORD: qwer1234
       POSTGRES_USER: postgres
       POSTGRES_DB: postgres
       SCHEMA: public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5